export const areas = [
  { name: 'Administración' },
  { name: 'Negocios' },
  { name: 'Ingeniería Automotriz' },
  { name: 'Nanotecnología' },
  { name: 'Ingeniería Eléctrica' },
  { name: 'Energías Renovables' },
  { name: 'Materiales' },
  { name: 'Sistemas' },
  { name: 'Mecatrónica' },
  { name: 'Tecnologías de la Información' },
  { name: 'Manufactura' },
  { name: 'Mecánica' },
  { name: 'Logística' },
  { name: 'Cadena de Suministro' },
  { name: 'Aeronáutica' },
  { name: 'Dinámica de Vuelo' },
  { name: 'Electromovilidad' },
  { name: 'Industria Inteligente' },
  { name: 'Energía' },
  { name: 'Electrónica' },
  { name: 'Sostenibilidad' },
  { name: 'Ciencia de Datos' },
  { name: 'Inteligencia Artificial' },
  { name: 'Automatización' },
  { name: 'Gestión de Tecnología' },
  { name: 'Cómputo' },
]
